### ISSUE TITLE
Job State type incorrect

### ISSUE THREAD

**Issue by wereHamster** [googleapis/nodejs-scheduler#181]
Consider the following code which typechecks (see issue #180 why I have to inline the definition of State.ENABLED):

```
const [job] = await client.getJob({ name });
if (shouldRun && job.state !== 1 /* State.ENABLED */) {
  await client.resumeJob({ name });
}
```

The if branch will never be taken because the value of `job.state` is actually a string ("ENABLED") and not a number. Instead, I have to work around the typechecker like this:

```
const [job] = await client.getJob({ name });
if (shouldRun && (job.state as unknown) !== "ENABLED") {
  await client.resumeJob({ name });
}
```

#### Environment details

  - OS: GCP
  - Node.js version: 10
  - `@google-cloud/scheduler` version: 1.4.1

**Comment by bcoe** [comment]
@xiaozhenliu-gg5 @alexander-fenster feedback related to our generated types; is there a workaround that @wereHamster could use?

**Comment by alexander-fenster** [comment]
Hi again @wereHamster,

Again, we have this in plans. Enums are hard (mostly because our existing JS code used string everywhere, which turned out to be a huge problem when we started migrating to TypeScript since `pbts` - the tool we use for type definitions - generates proper `enum` fields). We are considering different options to fix it.

Try using `.fromObject` to make it work for you:

```ts
import * as protos from '@google-cloud/scheduler/build/protos/protos';

const [jobObj] = await client.getJob({ name });
const job = protos.google.cloud.scheduler.v1.Job.fromObject(jobObj);
```

This might help for the time being while we're working on a proper fix.

**Comment by alexander-fenster** [comment]
@wereHamster The fix for this is released, enum now support strings. Please let us know if you need any help here, I'm going to close this issue for now.
